<?php

/**
 * DBKBTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DBKBTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DBKBTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DBKB');
    }
}