<?php

/**
 * JenisPermohonanTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class JenisPermohonanTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object JenisPermohonanTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('JenisPermohonan');
    }
    
    public static function getJenisPermohonan()
    {
    	$q = self::getInstance()
    		->createQuery('a')
    		->execute();
    		
    	return $q;
    }
}