<?php

/**
 * kelurahanTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class kelurahanTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object kelurahanTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('kelurahan');
    }
}