<?php

/**
 * LSPOPTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LSPOPTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LSPOPTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('LSPOP');
    }
}