<?php

/**
 * NJOPTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class NJOPTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object NJOPTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('NJOP');
    }
}