<?php

/**
 * ObjekPajakTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ObjekPajakTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ObjekPajakTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ObjekPajak');
    }
}