<?php

/**
 * opsiTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class opsiTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object opsiTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('opsi');
    }
}