<?php

/**
 * PermohonanTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PermohonanTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PermohonanTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Permohonan');
    }
    
    static public $jenis_surat = array(
    	'individual' => 'Individual',
    	'kolektif' => 'Kolektif',
  	);
 
  	public function getJenisSurat()
  	{
    	return self::$jenis_surat;
  	}
}