<?php

/**
 * ZNTTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ZNTTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ZNTTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ZNT');
    }
}