# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:

  metas:
    viewport:     width=device-width, initial-scale=1.0
    description:  symfony project
    author:
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    [bootstrap.css,bootstrap-responsive.css,docs.css,google-code-prettify/prettify.css]

  javascripts:    [jquery.js,google-code-prettify/prettify.js,bootstrap-transition.js,bootstrap-alert.js,bootstrap-modal.js,bootstrap-dropdown.js,bootstrap-scrollspy.js,bootstrap-tab.js,bootstrap-tooltip.js,bootstrap-popover.js,bootstrap-button.js,bootstrap-collapse.js,bootstrap-carousel.js,bootstrap-typeahead.js,application.js]

  has_layout:     true
  layout:         layout
